INSTALL         = install
INSTALL_PROGRAM = $(INSTALL)
RM              = rm -f
RM_DIR          = rm -rf

LUA_VERSION= 5.4

# Generated by ./configure
include config.mk


# Standard targets

all: pallene-tracer lpeg

clean:
	cd ./deps/pallene-tracer && $(MAKE) clean
	cd ./deps/lpeg           && $(MAKE) clean

distclean: clean
	$(RM) config.mk

install: all
	# Any change in the 'install' target should, probably, induce
	# a corresponding change in the 'uninstall' target.

	# Make all the requisite directories.
	mkdir -p $(INSTALL_PREFIX)/include
	mkdir -p $(INSTALL_PREFIX)/bin
	mkdir -p $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)
	mkdir -p $(INSTALL_PREFIX)/lib/lua/$(LUA_VERSION)

	# Install all the dependencies first.
	cd deps/pallene-tracer && $(MAKE) install PREFIX=$(INSTALL_PREFIX)

	# Note that we have to manually copy these over because
	# the Makefile for these projects do not provide an 'install'
	# target.
	$(INSTALL) -D deps/argparse/src/argparse.lua $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)
	$(INSTALL) -D deps/lpeg/re.lua               $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)
	$(INSTALL) -D deps/lpeg/lpeg.so              $(INSTALL_PREFIX)/lib/lua/$(LUA_VERSION)

	# Install Pallene.
	cp -r src/pallene $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)
	cp -r src/bin     $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)

	# Install the wrapper shell script (inspired by LuaRocks).
	$(INSTALL_PROGRAM) -D pallenec $(INSTALL_PREFIX)/bin

uninstall:
	# Uninstall all the dependencies.
	cd ./deps/pallene-tracer && $(MAKE) uninstall PREFIX=$(INSTALL_PREFIX)
	$(RM)     $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)/argparse.lua
	$(RM)     $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)/re.lua
	$(RM)     $(INSTALL_PREFIX)/lib/lua/$(LUA_VERSION)/lpeg.so

	# Uninstall Pallene.
	$(RM_DIR) $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)/pallene
	$(RM_DIR) $(INSTALL_PREFIX)/share/lua/$(LUA_VERSION)/bin

	# Uninstall the wrapper shell script (inspired by LuaRocks).
	$(RM) $(INSTALL_PREFIX)/bin/pallenec

.PHONY: all clean distclean install uninstall pallene-tracer lpeg

# Compilation

pallene-tracer:
	cd ./deps/pallene-tracer  && $(MAKE)

lpeg:
	cd ./deps/lpeg            && $(MAKE)

config.mk:
	@echo You must run ./configure before make
	@exit 1
