#!/bin/sh

space=' '
tab='	'
ok=yes

red='\033[1;31m'
green='\033[1;32m'
reset='\033[0m'

error() {
    printf "${red}ERROR${reset} %s\n" "$*"
    ok=no
}

echo "--- Lua Lint ---"
luacheck pallene/ spec/ examples/ "$@" || exit 1
echo

echo "--- Other checks ---"
for file in \
    pallene/*.lua spec/*.lua \
    examples/*/*.lua examples/*/*.pln \
    vm/src/pallene_core.c vm/src/pallene_core.h
do
    if grep --line-number "[$space$tab]$" "$file"; then
        # Forbid trailing whitespace because some editors like to automatically delete it.
        # Such whitespace can cause spurious diffs later down the road, when someone is working on
        # an unrelated pull request and their editor "helpfully" deletes the trailing whitespace.
        error "File $file has a line that ends in whitespace"
    fi

    if grep --line-number "^$tab" "$file"; then
        # Standardize on spaces because mixing tabs and spaces is endless pain.
        error "File $file has tab-based indentation"
    fi

    if ! grep --line-number --quiet 'SPDX-License-Identifier' "$file"; then
        error "File $file is missing a copyright header"
    fi
done

if [ "$ok" != yes ]; then
    exit 1
fi

printf "${green}OK${reset}\n"
