#!/bin/sh

# We encourage our developers to use busted --no-keep-going by default. Sometimes the test suite
# is failing because of something silly such as forgetting to run make and in those cases there is
# a desire to interrupt the test suite with Ctrl-C. With --keep-going (the default busted behavior)
# you need to press Ctrl-C multiple times and one of those Ctrl-C's will likely kill the busted
# process itself, meaning that the "teardown" routines are not run. On the other hand, with
# --no-keep-going we only need to press Ctrl-C once and busted usually gets to exit gracefully.

busted --no-keep-going "$@"
