#!/usr/bin/env lua

local argparse = require 'argparse'

local checker = require 'titan-compiler.checker'
local coder = require 'titan-compiler.coder'
local parser = require 'titan-compiler.parser'
local util = require 'titan-compiler.util'
local pretty = require 'titan-compiler.pretty'
local driver = require 'titan-compiler.driver'

local p = argparse('titan', 'Titan compiler')
p:argument('module', 'Names of the modules to compile.'):args("+")
p:flag('--print-ast', 'Print the AST.')
p:option('-l --lua', 'Path to Lua source tree (to find Lua headers, defaults to "lua/src").')
p:option('-t --tree', 'Root of the source tree, used for looking for source modules (defaults to ".").')
local args = p:parse()

-- Work like assert, but don't print the stack trace
local function exit(msg)
    io.stderr:write(msg, "\n")
    os.exit(1)
end

driver.TITAN_SOURCE_PATH = args.tree or driver.TITAN_SOURCE_PATH
driver.LUA_SOURCE_PATH = args.lua or driver.LUA_SOURCE_PATH

local errors = {}

for _, modname in ipairs(args.module) do
    local ok, errs = checker.checkimport(modname, driver.defaultloader)
    if not ok then 
        table.insert(errors, errs)
    else
        if #errs > 0 then table.insert(errors, table.concat(errs, "\n")) end
        local ast = driver.imported[modname].ast
        if args.print_ast and ast then
            print(parser.pretty_print_ast(ast))
        end
    end
end

if #errors > 0 then exit(table.concat(errors, "\n")) end

for name, mod in pairs(driver.imported) do
    local ok, err = driver.compile_module(name, mod)
    if not ok then table.insert(errors, err) end
end

if #errors > 0 then exit(table.concat(errors, "\n")) end
