/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static Table * function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* depth */
);
static lua_Integer function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1  /* tree */
);
static Table * function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* mindepth */
    lua_Integer x2, /* maxdepth */
    lua_Integer x3  /* depth */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
  done:
    return;
}

/* BottomUpTree size_comparison/binarytrees_pln.pln:1 */
static Table * function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* depth */
) {
    luaD_checkstack(L, 3);
    Table * x2; /* ret1 */
    Table * x3; /* left */
    Table * x4; /* right */
    int x5;
    TValue x6;
    TValue x7;
    TValue x8;
    TValue x9;
    	
    x5 = (x1 > 0);
    if (x5) {
        x1 = intop(-, x1, 1);
        {
            StackValue *old_stack = L->stack;
            x3 = function_02(L, G, base + 0, x1);
            base = L->stack + (base - old_stack);
        }
        sethvalue(L, s2v(base + 0), x3);
        {
            StackValue *old_stack = L->stack;
            x4 = function_02(L, G, base + 1, x1);
            base = L->stack + (base - old_stack);
        }
        sethvalue(L, s2v(base + 1), x4);
        x2 = pallene_createtable(L, 2, 0);
        sethvalue(L, s2v(base + 2), x2);
        luaC_condGC(L, L->top = base + 3, (void)0);
        sethvalue(L, &x6, x3);
        {
            pallene_renormalize_array(L, x2, 1, 6);
            TValue *slot = &x2->array[1 - 1];
            setobj(L, slot, &x6);
            pallene_barrierback_unknown_child(L, x2, &x6);
        }
        sethvalue(L, &x7, x4);
        {
            pallene_renormalize_array(L, x2, 2, 6);
            TValue *slot = &x2->array[2 - 1];
            setobj(L, slot, &x7);
            pallene_barrierback_unknown_child(L, x2, &x7);
        }
        goto done;
    } else {
        x2 = pallene_createtable(L, 2, 0);
        sethvalue(L, s2v(base + 2), x2);
        luaC_condGC(L, L->top = base + 3, (void)0);
        setbvalue(&x8, 0);
        {
            pallene_renormalize_array(L, x2, 1, 8);
            TValue *slot = &x2->array[1 - 1];
            setobj(L, slot, &x8);
            pallene_barrierback_unknown_child(L, x2, &x8);
        }
        setbvalue(&x9, 0);
        {
            pallene_renormalize_array(L, x2, 2, 8);
            TValue *slot = &x2->array[2 - 1];
            setobj(L, slot, &x9);
            pallene_barrierback_unknown_child(L, x2, &x9);
        }
        goto done;
    }
    	
  done:
    return x2;
}

/* ItemCheck size_comparison/binarytrees_pln.pln:12 */
static lua_Integer function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1  /* tree */
) {
    luaD_checkstack(L, 1);
    lua_Integer x2; /* ret1 */
    TValue x3;
    int x4;
    lua_Integer x5;
    lua_Integer x6;
    Table * x7;
    TValue x8;
    lua_Integer x9;
    Table * x10;
    TValue x11;
    	
    {
        pallene_renormalize_array(L, x1, 1, 13);
        TValue *slot = &x1->array[1 - 1];
        x3 = *(slot);
        if (isempty(&x3)) {
            setnilvalue(&x3);
        }
    }
    x4 = pallene_is_truthy(&x3);
    if (x4) {
        {
            pallene_renormalize_array(L, x1, 1, 14);
            TValue *slot = &x1->array[1 - 1];
            x8 = *(slot);
            if (isempty(&x8)) {
                setnilvalue(&x8);
            }
        }
        if (PALLENE_UNLIKELY(!ttistable(&x8))) {
            pallene_runtime_tag_check_error(L,
                14, LUA_TTABLE, rawtt(&x8),
                "downcasted value");
        }
        x7 = hvalue(&x8);
        sethvalue(L, s2v(base + 0), x7);
        {
            StackValue *old_stack = L->stack;
            x6 = function_03(L, G, base + 1, x7);
            base = L->stack + (base - old_stack);
        }
        x5 = intop(+, 1, x6);
        {
            pallene_renormalize_array(L, x1, 2, 14);
            TValue *slot = &x1->array[2 - 1];
            x11 = *(slot);
            if (isempty(&x11)) {
                setnilvalue(&x11);
            }
        }
        if (PALLENE_UNLIKELY(!ttistable(&x11))) {
            pallene_runtime_tag_check_error(L,
                14, LUA_TTABLE, rawtt(&x11),
                "downcasted value");
        }
        x10 = hvalue(&x11);
        sethvalue(L, s2v(base + 0), x10);
        {
            StackValue *old_stack = L->stack;
            x9 = function_03(L, G, base + 1, x10);
            base = L->stack + (base - old_stack);
        }
        x2 = intop(+, x5, x9);
        goto done;
    } else {
        x2 = 1;
        goto done;
    }
    	
  done:
    return x2;
}

/* Stress size_comparison/binarytrees_pln.pln:20 */
static Table * function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* mindepth */
    lua_Integer x2, /* maxdepth */
    lua_Integer x3  /* depth */
) {
    luaD_checkstack(L, 1);
    Table * x4; /* ret1 */
    lua_Integer x5; /* iterations */
    lua_Integer x6; /* check */
    lua_Integer x7; /* _ */
    Table * x8; /* t */
    lua_Integer x9;
    lua_Integer x10;
    lua_Integer x11;
    	
    x10 = intop(-, x2, x3);
    x9 = intop(+, x10, x1);
    x5 = pallene_shiftL(1, x9);
    x6 = 0;
    for(
        lua_Integer start01 = 1, limit01 = x5, step01 = 1;
        (step01 >= 0 ? start01 <= limit01 : start01 >= limit01);
        start01 = intop(+, start01, step01)
    ){
        x7 = start01;
        {
            StackValue *old_stack = L->stack;
            x8 = function_02(L, G, base + 0, x3);
            base = L->stack + (base - old_stack);
        }
        sethvalue(L, s2v(base + 0), x8);
        {
            StackValue *old_stack = L->stack;
            x11 = function_03(L, G, base + 1, x8);
            base = L->stack + (base - old_stack);
        }
        x6 = intop(+, x6, x11);
    }
    x4 = pallene_createtable(L, 2, 0);
    sethvalue(L, s2v(base + 0), x4);
    luaC_condGC(L, L->top = base + 1, (void)0);
    {
        pallene_renormalize_array(L, x4, 1, 27);
        TValue *slot = &x4->array[1 - 1];
        setivalue(slot, x5);
    }
    {
        pallene_renormalize_array(L, x4, 2, 27);
        TValue *slot = &x4->array[2 - 1];
        setivalue(slot, x6);
    }
    goto done;
    	
  done:
    return x4;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "BottomUpTree", 1, nargs);
    }
    	
    lua_Integer x1;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            1, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "depth");
    }
    x1 = ivalue(s2v(base + 1));
    	
    Table * ret1;
    ret1 = function_02(L, G, L->top, x1);
    sethvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_03_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "ItemCheck", 1, nargs);
    }
    	
    Table * x1;
    	
    if (PALLENE_UNLIKELY(!ttistable(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            12, LUA_TTABLE, rawtt(s2v(base + 1)),
            "argument '%s'", "tree");
    }
    x1 = hvalue(s2v(base + 1));
    	
    lua_Integer ret1;
    ret1 = function_03(L, G, L->top, x1);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_04_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 3)) {
        pallene_runtime_arity_error(L, "Stress", 3, nargs);
    }
    	
    lua_Integer x1;
    lua_Integer x2;
    lua_Integer x3;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            20, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "mindepth");
    }
    x1 = ivalue(s2v(base + 1));
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 2)))) {
        pallene_runtime_tag_check_error(L,
            20, LUA_TNUMINT, rawtt(s2v(base + 2)),
            "argument '%s'", "maxdepth");
    }
    x2 = ivalue(s2v(base + 2));
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 3)))) {
        pallene_runtime_tag_check_error(L,
            20, LUA_TNUMINT, rawtt(s2v(base + 3)),
            "argument '%s'", "depth");
    }
    x3 = ivalue(s2v(base + 3));
    	
    Table * ret1;
    ret1 = function_04(L, G, L->top, x1, x2, x3);
    sethvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

int luaopen_size_comparison_binarytrees_pln(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 0);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 4, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_seti(L, closures, 2);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_03_lua, 1);
    lua_seti(L, closures, 3);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_04_lua, 1);
    lua_seti(L, closures, 4);
    	
    /* Global values */
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "BottomUpTree");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "ItemCheck");
    lua_geti(L, closures, 3);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "Stress");
    lua_geti(L, closures, 4);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

