/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static Table * function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* N */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
  done:
    return;
}

/* fannkuch size_comparison/fannkuchredux_pln.pln:1 */
static Table * function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* N */
) {
    luaD_checkstack(L, 4);
    Table * x2; /* ret1 */
    Table * x3; /* initial_perm */
    lua_Integer x4; /* i */
    Table * x5; /* perm */
    Table * x6; /* count */
    lua_Integer x7; /* r */
    lua_Integer x8; /* perm_count */
    lua_Integer x9; /* max_flips */
    lua_Integer x10; /* checksum */
    lua_Integer x11; /* i */
    lua_Integer x12; /* flips_count */
    lua_Integer x13; /* h */
    lua_Integer x14; /* i */
    lua_Integer x15; /* j */
    lua_Integer x16; /* a */
    lua_Integer x17; /* b */
    lua_Integer x18; /* tmp */
    lua_Integer x19; /* i */
    lua_Integer x20; /* r1 */
    lua_Integer x21;
    int x22;
    int x23;
    int x24;
    int x25;
    lua_Integer x26;
    int x27;
    int x28;
    lua_Integer x29;
    lua_Integer x30;
    lua_Integer x31;
    lua_Integer x32;
    lua_Integer x33;
    int x34;
    lua_Integer x35;
    	
    x3 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 0), x3);
    luaC_condGC(L, L->top = base + 1, (void)0);
    for(
        lua_Integer start01 = 1, limit01 = x1, step01 = 1;
        (step01 >= 0 ? start01 <= limit01 : start01 >= limit01);
        start01 = intop(+, start01, step01)
    ){
        x4 = start01;
        {
            pallene_renormalize_array(L, x3, x4, 5);
            TValue *slot = &x3->array[x4 - 1];
            setivalue(slot, x4);
        }
    }
    x5 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 1), x5);
    luaC_condGC(L, L->top = base + 2, (void)0);
    x6 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 2), x6);
    luaC_condGC(L, L->top = base + 3, (void)0);
    {
        pallene_renormalize_array(L, x6, 1, 11);
        TValue *slot = &x6->array[1 - 1];
        setivalue(slot, 0);
    }
    x7 = x1;
    x8 = 0;
    x9 = 0;
    x10 = 0;
    while (1) {
        for(
            lua_Integer start02 = 1, limit02 = x1, step02 = 1;
            (step02 >= 0 ? start02 <= limit02 : start02 >= limit02);
            start02 = intop(+, start02, step02)
        ){
            x11 = start02;
            {
                pallene_renormalize_array(L, x3, x11, 24);
                TValue *slot = &x3->array[x11 - 1];
                if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                    pallene_runtime_tag_check_error(L,
                        24, LUA_TNUMINT, rawtt(slot),
                        "array element");
                }
                x21 = ivalue(slot);
            }
            {
                pallene_renormalize_array(L, x5, x11, 24);
                TValue *slot = &x5->array[x11 - 1];
                setivalue(slot, x21);
            }
        }
        x12 = 0;
        {
            pallene_renormalize_array(L, x5, 1, 28);
            TValue *slot = &x5->array[1 - 1];
            if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                pallene_runtime_tag_check_error(L,
                    28, LUA_TNUMINT, rawtt(slot),
                    "array element");
            }
            x13 = ivalue(slot);
        }
        while (1) {
            x22 = (x13 > 1);
            if (!x22) {
                break;
            }
            x14 = 1;
            x15 = x13;
            while (1) {
                {
                    pallene_renormalize_array(L, x5, x14, 33);
                    TValue *slot = &x5->array[x14 - 1];
                    if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                        pallene_runtime_tag_check_error(L,
                            33, LUA_TNUMINT, rawtt(slot),
                            "array element");
                    }
                    x16 = ivalue(slot);
                }
                {
                    pallene_renormalize_array(L, x5, x15, 34);
                    TValue *slot = &x5->array[x15 - 1];
                    if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                        pallene_runtime_tag_check_error(L,
                            34, LUA_TNUMINT, rawtt(slot),
                            "array element");
                    }
                    x17 = ivalue(slot);
                }
                {
                    pallene_renormalize_array(L, x5, x14, 35);
                    TValue *slot = &x5->array[x14 - 1];
                    setivalue(slot, x17);
                }
                {
                    pallene_renormalize_array(L, x5, x15, 36);
                    TValue *slot = &x5->array[x15 - 1];
                    setivalue(slot, x16);
                }
                x14 = intop(+, x14, 1);
                x15 = intop(-, x15, 1);
                x23 = (x14 >= x15);
                if (x23) {
                    break;
                }
            }
            x12 = intop(+, x12, 1);
            {
                pallene_renormalize_array(L, x5, 1, 42);
                TValue *slot = &x5->array[1 - 1];
                if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                    pallene_runtime_tag_check_error(L,
                        42, LUA_TNUMINT, rawtt(slot),
                        "array element");
                }
                x13 = ivalue(slot);
            }
        }
        x24 = (x12 > x9);
        if (x24) {
            x9 = x12;
        }
        x26 = pallene_int_modi(L, x8, 2, 49);
        x25 = (x26 == 0);
        if (x25) {
            x10 = intop(+, x10, x12);
        } else {
            x10 = intop(-, x10, x12);
        }
        while (1) {
            x27 = (x7 > 1);
            if (!x27) {
                break;
            }
            {
                pallene_renormalize_array(L, x6, x7, 59);
                TValue *slot = &x6->array[x7 - 1];
                setivalue(slot, x7);
            }
            x7 = intop(-, x7, 1);
        }
        while (1) {
            x28 = (x7 == x1);
            if (x28) {
                x2 = pallene_createtable(L, 2, 0);
                sethvalue(L, s2v(base + 3), x2);
                luaC_condGC(L, L->top = base + 4, (void)0);
                {
                    pallene_renormalize_array(L, x2, 1, 65);
                    TValue *slot = &x2->array[1 - 1];
                    setivalue(slot, x10);
                }
                {
                    pallene_renormalize_array(L, x2, 2, 65);
                    TValue *slot = &x2->array[2 - 1];
                    setivalue(slot, x9);
                }
                goto done;
            }
            {
                pallene_renormalize_array(L, x3, 1, 68);
                TValue *slot = &x3->array[1 - 1];
                if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                    pallene_runtime_tag_check_error(L,
                        68, LUA_TNUMINT, rawtt(slot),
                        "array element");
                }
                x18 = ivalue(slot);
            }
            for(
                lua_Integer start03 = 1, limit03 = x7, step03 = 1;
                (step03 >= 0 ? start03 <= limit03 : start03 >= limit03);
                start03 = intop(+, start03, step03)
            ){
                x19 = start03;
                x30 = intop(+, x19, 1);
                {
                    pallene_renormalize_array(L, x3, x30, 70);
                    TValue *slot = &x3->array[x30 - 1];
                    if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                        pallene_runtime_tag_check_error(L,
                            70, LUA_TNUMINT, rawtt(slot),
                            "array element");
                    }
                    x29 = ivalue(slot);
                }
                {
                    pallene_renormalize_array(L, x3, x19, 70);
                    TValue *slot = &x3->array[x19 - 1];
                    setivalue(slot, x29);
                }
            }
            x31 = intop(+, x7, 1);
            {
                pallene_renormalize_array(L, x3, x31, 72);
                TValue *slot = &x3->array[x31 - 1];
                setivalue(slot, x18);
            }
            x20 = intop(+, x7, 1);
            {
                pallene_renormalize_array(L, x6, x20, 75);
                TValue *slot = &x6->array[x20 - 1];
                if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                    pallene_runtime_tag_check_error(L,
                        75, LUA_TNUMINT, rawtt(slot),
                        "array element");
                }
                x33 = ivalue(slot);
            }
            x32 = intop(-, x33, 1);
            {
                pallene_renormalize_array(L, x6, x20, 75);
                TValue *slot = &x6->array[x20 - 1];
                setivalue(slot, x32);
            }
            {
                pallene_renormalize_array(L, x6, x20, 76);
                TValue *slot = &x6->array[x20 - 1];
                if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                    pallene_runtime_tag_check_error(L,
                        76, LUA_TNUMINT, rawtt(slot),
                        "array element");
                }
                x35 = ivalue(slot);
            }
            x34 = (x35 > 0);
            if (x34) {
                break;
            }
            x7 = x20;
        }
        x8 = intop(+, x8, 1);
    }
    	
  done:
    return x2;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "fannkuch", 1, nargs);
    }
    	
    lua_Integer x1;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            1, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "N");
    }
    x1 = ivalue(s2v(base + 1));
    	
    Table * ret1;
    ret1 = function_02(L, G, L->top, x1);
    sethvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

int luaopen_size_comparison_fannkuchredux_pln(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 0);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 2, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_seti(L, closures, 2);
    	
    /* Global values */
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "fannkuch");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

