/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Number function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Number x1  /* max */
);
static void function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    TString * x1, /* id */
    TString * x2  /* desc */
);
static void function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    TString * x1, /* id */
    TString * x2, /* desc */
    TString * x3, /* alu */
    lua_Integer x4  /* n */
);
static lua_Integer function_05(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1, /* ps */
    lua_Number x2  /* p */
);
static void function_06(
    lua_State *L,
    Udata *G,
    StackValue *base,
    TString * x1, /* id */
    TString * x2, /* desc */
    Table * x3, /* frequencies */
    lua_Integer x4  /* n */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
    setivalue(&G->uv[7].uv, 42);
    	
  done:
    return;
}

/* random size_comparison/fasta_pln.pln:6 */
static lua_Number function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Number x1  /* max */
) {
    lua_Number x2; /* ret1 */
    lua_Integer x3;
    lua_Integer x4;
    lua_Integer x5;
    lua_Integer x6;
    lua_Integer x7;
    lua_Integer x8;
    lua_Integer x9;
    lua_Number x10;
    lua_Number x11;
    lua_Integer x12;
    lua_Number x13;
    lua_Integer x14;
    	
    x6 = ivalue(&G->uv[7].uv);
    x7 = 3877;
    x5 = intop(*, x6, x7);
    x8 = 29573;
    x4 = intop(+, x5, x8);
    x9 = 139968;
    x3 = pallene_int_modi(L, x4, x9, 7);
    setivalue(&G->uv[7].uv, x3);
    x12 = ivalue(&G->uv[7].uv);
    x11 = (lua_Number) x12;
    x10 = x1 * x11;
    x14 = 139968;
    x13 = (lua_Number) x14;
    x2 = x10 / x13;
    goto done;
    	
  done:
    return x2;
}

/* print_fasta_header size_comparison/fasta_pln.pln:13 */
static void function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    TString * x1, /* id */
    TString * x2  /* desc */
) {
    luaD_checkstack(L, 1);
    TString * x3;
    	
    {
        TString *ss[5];
        ss[0] = tsvalue(&G->uv[0].uv);
        ss[1] = x1;
        ss[2] = tsvalue(&G->uv[1].uv);
        ss[3] = x2;
        ss[4] = tsvalue(&G->uv[6].uv); ;
        x3 = pallene_string_concatN(L, 5, ss);
    }
    setsvalue(L, s2v(base + 0), x3);
    luaC_condGC(L, L->top = base + 1, (void)0);
    pallene_io_write(L, x3);
    	
  done:
    return;
}

/* repeat_fasta size_comparison/fasta_pln.pln:17 */
static void function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    TString * x1, /* id */
    TString * x2, /* desc */
    TString * x3, /* alu */
    lua_Integer x4  /* n */
) {
    luaD_checkstack(L, 2);
    lua_Integer x5; /* alusize */
    TString * x6; /* aluwrap */
    lua_Integer x7; /* lines */
    lua_Integer x8; /* last_line */
    lua_Integer x9; /* start */
    lua_Integer x10; /* _ */
    lua_Integer x11; /* stop */
    int x12;
    lua_Integer x13;
    lua_Integer x14;
    lua_Integer x15;
    lua_Integer x16;
    lua_Integer x17;
    lua_Integer x18;
    TString * x19;
    lua_Integer x20;
    int x21;
    TString * x22;
    lua_Integer x23;
    lua_Integer x24;
    	
    {
        StackValue *old_stack = L->stack;
        function_03(L, G, base + 0, x1, x2);
        base = L->stack + (base - old_stack);
    }
    x5 = tsslen(x3);
    {
        TString *ss[2];
        ss[0] = x3;
        ss[1] = x3; ;
        x6 = pallene_string_concatN(L, 2, ss);
    }
    setsvalue(L, s2v(base + 0), x6);
    luaC_condGC(L, L->top = base + 1, (void)0);
    while (1) {
        x13 = tsslen(x6);
        x15 = 60;
        x14 = intop(+, x5, x15);
        x12 = (x13 < x14);
        if (!x12) {
            break;
        }
        {
            TString *ss[2];
            ss[0] = x6;
            ss[1] = x3; ;
            x6 = pallene_string_concatN(L, 2, ss);
        }
        setsvalue(L, s2v(base + 0), x6);
        luaC_condGC(L, L->top = base + 1, (void)0);
    }
    x16 = 60;
    x7 = pallene_int_divi(L, x4, x16, 27);
    x17 = 60;
    x8 = pallene_int_modi(L, x4, x17, 28);
    x9 = 0;
    for(
        lua_Integer start01 = 1, limit01 = x7, step01 = 1;
        (step01 >= 0 ? start01 <= limit01 : start01 >= limit01);
        start01 = intop(+, start01, step01)
    ){
        x10 = start01;
        x18 = 60;
        x11 = intop(+, x9, x18);
        x20 = intop(+, x9, 1);
        x19 = pallene_string_sub(L, x6, x20, x11);
        setsvalue(L, s2v(base + 1), x19);
        luaC_condGC(L, L->top = base + 2, (void)0);
        pallene_io_write(L, x19);
        pallene_io_write(L, tsvalue(&G->uv[6].uv));
        x9 = pallene_int_modi(L, x11, x5, 34);
    }
    x21 = (x8 > 0);
    if (x21) {
        x23 = intop(+, x9, 1);
        x24 = intop(+, x9, x8);
        x22 = pallene_string_sub(L, x6, x23, x24);
        setsvalue(L, s2v(base + 0), x22);
        luaC_condGC(L, L->top = base + 1, (void)0);
        pallene_io_write(L, x22);
        pallene_io_write(L, tsvalue(&G->uv[6].uv));
    }
    	
  done:
    return;
}

/* linear_search size_comparison/fasta_pln.pln:42 */
static lua_Integer function_05(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1, /* ps */
    lua_Number x2  /* p */
) {
    lua_Integer x3; /* ret1 */
    lua_Integer x4; /* i */
    lua_Integer x5;
    int x6;
    lua_Number x7;
    	
    x5 = luaH_getn(x1);
    for(
        lua_Integer start02 = 1, limit02 = x5, step02 = 1;
        (step02 >= 0 ? start02 <= limit02 : start02 >= limit02);
        start02 = intop(+, start02, step02)
    ){
        x4 = start02;
        {
            pallene_renormalize_array(L, x1, x4, 44);
            TValue *slot = &x1->array[x4 - 1];
            if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
                pallene_runtime_tag_check_error(L,
                    44, LUA_TNUMFLT, rawtt(slot),
                    "array element");
            }
            x7 = fltvalue(slot);
        }
        x6 = (x7 >= x2);
        if (x6) {
            x3 = x4;
            goto done;
        }
    }
    x3 = 1;
    goto done;
    	
  done:
    return x3;
}

/* random_fasta size_comparison/fasta_pln.pln:51 */
static void function_06(
    lua_State *L,
    Udata *G,
    StackValue *base,
    TString * x1, /* id */
    TString * x2, /* desc */
    Table * x3, /* frequencies */
    lua_Integer x4  /* n */
) {
    luaD_checkstack(L, 2);
    lua_Integer x5; /* nitems */
    Table * x6; /* letters */
    Table * x7; /* probs */
    lua_Number x8; /* total */
    lua_Integer x9; /* i */
    Table * x10; /* o */
    TString * x11; /* c */
    lua_Number x12; /* p */
    lua_Integer x13; /* col */
    lua_Integer x14; /* _ */
    lua_Integer x15; /* ix */
    TString * x16; /* c */
    TValue x17;
    TValue x18;
    lua_Number x19;
    int x20;
    lua_Integer x21;
    int x22;
    	
    {
        StackValue *old_stack = L->stack;
        function_03(L, G, base + 0, x1, x2);
        base = L->stack + (base - old_stack);
    }
    x5 = luaH_getn(x3);
    x6 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 0), x6);
    luaC_condGC(L, L->top = base + 1, (void)0);
    x7 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 1), x7);
    luaC_condGC(L, L->top = base + 2, (void)0);
    x8 = 0.0;
    for(
        lua_Integer start03 = 1, limit03 = x5, step03 = 1;
        (step03 >= 0 ? start03 <= limit03 : start03 >= limit03);
        start03 = intop(+, start03, step03)
    ){
        x9 = start03;
        {
            pallene_renormalize_array(L, x3, x9, 61);
            TValue *slot = &x3->array[x9 - 1];
            if (PALLENE_UNLIKELY(!ttistable(slot))) {
                pallene_runtime_tag_check_error(L,
                    61, LUA_TTABLE, rawtt(slot),
                    "array element");
            }
            x10 = hvalue(slot);
        }
        {
            pallene_renormalize_array(L, x10, 1, 62);
            TValue *slot = &x10->array[1 - 1];
            x17 = *(slot);
            if (isempty(&x17)) {
                setnilvalue(&x17);
            }
        }
        if (PALLENE_UNLIKELY(!ttisstring(&x17))) {
            pallene_runtime_tag_check_error(L,
                62, LUA_TSTRING, rawtt(&x17),
                "downcasted value");
        }
        x11 = tsvalue(&x17);
        {
            pallene_renormalize_array(L, x10, 2, 63);
            TValue *slot = &x10->array[2 - 1];
            x18 = *(slot);
            if (isempty(&x18)) {
                setnilvalue(&x18);
            }
        }
        if (PALLENE_UNLIKELY(!ttisfloat(&x18))) {
            pallene_runtime_tag_check_error(L,
                63, LUA_TNUMFLT, rawtt(&x18),
                "downcasted value");
        }
        x12 = fltvalue(&x18);
        x8 = x8 + x12;
        {
            pallene_renormalize_array(L, x6, x9, 65);
            TValue *slot = &x6->array[x9 - 1];
            setsvalue(L, slot, x11);
            pallene_barrierback_collectable_child(L, x6, x11);
        }
        {
            pallene_renormalize_array(L, x7, x9, 66);
            TValue *slot = &x7->array[x9 - 1];
            setfltvalue(slot, x8);
        }
    }
    {
        pallene_renormalize_array(L, x7, x5, 68);
        TValue *slot = &x7->array[x5 - 1];
        setfltvalue(slot, 1.0);
    }
    x13 = 0;
    for(
        lua_Integer start04 = 1, limit04 = x4, step04 = 1;
        (step04 >= 0 ? start04 <= limit04 : start04 >= limit04);
        start04 = intop(+, start04, step04)
    ){
        x14 = start04;
        {
            StackValue *old_stack = L->stack;
            x19 = function_02(L, G, base + 2, 1.0);
            base = L->stack + (base - old_stack);
        }
        {
            StackValue *old_stack = L->stack;
            x15 = function_05(L, G, base + 2, x7, x19);
            base = L->stack + (base - old_stack);
        }
        {
            pallene_renormalize_array(L, x6, x15, 75);
            TValue *slot = &x6->array[x15 - 1];
            if (PALLENE_UNLIKELY(!ttisstring(slot))) {
                pallene_runtime_tag_check_error(L,
                    75, LUA_TSTRING, rawtt(slot),
                    "array element");
            }
            x16 = tsvalue(slot);
        }
        pallene_io_write(L, x16);
        x13 = intop(+, x13, 1);
        x21 = 60;
        x20 = (x13 >= x21);
        if (x20) {
            pallene_io_write(L, tsvalue(&G->uv[6].uv));
            x13 = 0;
        }
    }
    x22 = (x13 > 0);
    if (x22) {
        pallene_io_write(L, tsvalue(&G->uv[6].uv));
    }
    	
  done:
    return;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_04_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 4)) {
        pallene_runtime_arity_error(L, "repeat_fasta", 4, nargs);
    }
    	
    TString * x1;
    TString * x2;
    TString * x3;
    lua_Integer x4;
    	
    if (PALLENE_UNLIKELY(!ttisstring(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            17, LUA_TSTRING, rawtt(s2v(base + 1)),
            "argument '%s'", "id");
    }
    x1 = tsvalue(s2v(base + 1));
    	
    if (PALLENE_UNLIKELY(!ttisstring(s2v(base + 2)))) {
        pallene_runtime_tag_check_error(L,
            17, LUA_TSTRING, rawtt(s2v(base + 2)),
            "argument '%s'", "desc");
    }
    x2 = tsvalue(s2v(base + 2));
    	
    if (PALLENE_UNLIKELY(!ttisstring(s2v(base + 3)))) {
        pallene_runtime_tag_check_error(L,
            17, LUA_TSTRING, rawtt(s2v(base + 3)),
            "argument '%s'", "alu");
    }
    x3 = tsvalue(s2v(base + 3));
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 4)))) {
        pallene_runtime_tag_check_error(L,
            17, LUA_TNUMINT, rawtt(s2v(base + 4)),
            "argument '%s'", "n");
    }
    x4 = ivalue(s2v(base + 4));
    	
    function_04(L, G, L->top, x1, x2, x3, x4);
    return 0;
}

static int function_06_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 4)) {
        pallene_runtime_arity_error(L, "random_fasta", 4, nargs);
    }
    	
    TString * x1;
    TString * x2;
    Table * x3;
    lua_Integer x4;
    	
    if (PALLENE_UNLIKELY(!ttisstring(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            51, LUA_TSTRING, rawtt(s2v(base + 1)),
            "argument '%s'", "id");
    }
    x1 = tsvalue(s2v(base + 1));
    	
    if (PALLENE_UNLIKELY(!ttisstring(s2v(base + 2)))) {
        pallene_runtime_tag_check_error(L,
            51, LUA_TSTRING, rawtt(s2v(base + 2)),
            "argument '%s'", "desc");
    }
    x2 = tsvalue(s2v(base + 2));
    	
    if (PALLENE_UNLIKELY(!ttistable(s2v(base + 3)))) {
        pallene_runtime_tag_check_error(L,
            51, LUA_TTABLE, rawtt(s2v(base + 3)),
            "argument '%s'", "frequencies");
    }
    x3 = hvalue(s2v(base + 3));
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 4)))) {
        pallene_runtime_tag_check_error(L,
            51, LUA_TNUMINT, rawtt(s2v(base + 4)),
            "argument '%s'", "n");
    }
    x4 = ivalue(s2v(base + 4));
    	
    function_06(L, G, L->top, x1, x2, x3, x4);
    return 0;
}

int luaopen_size_comparison_fasta_pln(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 12);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 3, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_04_lua, 1);
    lua_seti(L, closures, 2);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_06_lua, 1);
    lua_seti(L, closures, 3);
    	
    /* Global values */
    	
    lua_pushstring(L, ">");
    lua_setiuservalue(L, globals, 1);
    	
    lua_pushstring(L, " ");
    lua_setiuservalue(L, globals, 2);
    	
    lua_pushstring(L, "\n");
    lua_setiuservalue(L, globals, 3);
    	
    lua_pushstring(L, "\n");
    lua_setiuservalue(L, globals, 4);
    	
    lua_pushstring(L, "\n");
    lua_setiuservalue(L, globals, 5);
    	
    lua_pushstring(L, "\n");
    lua_setiuservalue(L, globals, 6);
    	
    lua_pushstring(L, "\n");
    lua_setiuservalue(L, globals, 7);
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "repeat_fasta");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "random_fasta");
    lua_geti(L, closures, 3);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

