/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static void function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* N */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
  done:
    return;
}

/* mandelbrot size_comparison/mandelbrot_pln.pln:1 */
static void function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* N */
) {
    luaD_checkstack(L, 1);
    lua_Integer x2; /* bits */
    lua_Integer x3; /* nbits */
    lua_Number x4; /* delta */
    lua_Integer x5; /* y */
    lua_Number x6; /* Ci */
    lua_Integer x7; /* x */
    lua_Number x8; /* Cr */
    lua_Integer x9; /* bit */
    lua_Number x10; /* Zr */
    lua_Number x11; /* Zi */
    lua_Number x12; /* Zr2 */
    lua_Number x13; /* Zi2 */
    lua_Integer x14; /* _ */
    lua_Number x15;
    lua_Integer x16;
    lua_Number x17;
    lua_Number x18;
    lua_Integer x19;
    lua_Number x20;
    lua_Number x21;
    lua_Number x22;
    lua_Number x23;
    lua_Number x24;
    int x25;
    lua_Number x26;
    lua_Integer x27;
    int x28;
    TString * x29;
    int x30;
    lua_Integer x31;
    TString * x32;
    	
    x2 = 0;
    x3 = 0;
    x15 = (lua_Number) x1;
    x4 = 2.0 / x15;
    x16 = intop(-, x1, 1);
    for(
        lua_Integer start01 = 0, limit01 = x16, step01 = 1;
        (step01 >= 0 ? start01 <= limit01 : start01 >= limit01);
        start01 = intop(+, start01, step01)
    ){
        x5 = start01;
        x18 = (lua_Number) x5;
        x17 = x18 * x4;
        x6 = x17 - 1.0;
        x19 = intop(-, x1, 1);
        for(
            lua_Integer start02 = 0, limit02 = x19, step02 = 1;
            (step02 >= 0 ? start02 <= limit02 : start02 >= limit02);
            start02 = intop(+, start02, step02)
        ){
            x7 = start02;
            x21 = (lua_Number) x7;
            x20 = x21 * x4;
            x8 = x20 - 1.5;
            x9 = 1;
            x10 = 0.0;
            x11 = 0.0;
            x12 = 0.0;
            x13 = 0.0;
            for(
                lua_Integer start03 = 1, limit03 = 50, step03 = 1;
                (step03 >= 0 ? start03 <= limit03 : start03 >= limit03);
                start03 = intop(+, start03, step03)
            ){
                x14 = start03;
                x23 = 2.0 * x10;
                x22 = x23 * x11;
                x11 = x22 + x6;
                x24 = x12 - x13;
                x10 = x24 + x8;
                x13 = x11 * x11;
                x12 = x10 * x10;
                x26 = x13 + x12;
                x25 = (x26 > 4.0);
                if (x25) {
                    x9 = 0;
                    break;
                }
            }
            x27 = pallene_shiftL(x2, 1);
            x2 = intop(|, x27, x9);
            x3 = intop(+, x3, 1);
            x28 = (x3 == 8);
            if (x28) {
                x29 = pallene_string_char(L, x2, 31);
                setsvalue(L, s2v(base + 0), x29);
                luaC_condGC(L, L->top = base + 1, (void)0);
                pallene_io_write(L, x29);
                x2 = 0;
                x3 = 0;
            }
        }
        x30 = (x3 > 0);
        if (x30) {
            x31 = intop(-, 8, x3);
            x2 = pallene_shiftL(x2, x31);
            x32 = pallene_string_char(L, x2, 39);
            setsvalue(L, s2v(base + 0), x32);
            luaC_condGC(L, L->top = base + 1, (void)0);
            pallene_io_write(L, x32);
            x2 = 0;
            x3 = 0;
        }
    }
    	
  done:
    return;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "mandelbrot", 1, nargs);
    }
    	
    lua_Integer x1;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            1, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "N");
    }
    x1 = ivalue(s2v(base + 1));
    	
    function_02(L, G, L->top, x1);
    return 0;
}

int luaopen_size_comparison_mandelbrot_pln(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 0);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 2, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_seti(L, closures, 2);
    	
    /* Global values */
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "mandelbrot");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

