/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static void function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1, /* bi */
    Table * x2, /* bj */
    lua_Number x3  /* dt */
);
static void function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1, /* bi */
    lua_Number x2  /* dt */
);
static void function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* nsteps */
    Table * x2, /* bodies */
    lua_Number x3  /* dt */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
  done:
    return;
}

/* update_speeds size_comparison/nbodyTable_pln.pln:11 */
static void function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1, /* bi */
    Table * x2, /* bj */
    lua_Number x3  /* dt */
) {
    lua_Number x4; /* dx */
    lua_Number x5; /* dy */
    lua_Number x6; /* dz */
    lua_Number x7; /* dist */
    lua_Number x8; /* mag */
    lua_Number x9; /* bjm */
    lua_Number x10; /* bim */
    lua_Number x11;
    lua_Number x12;
    lua_Number x13;
    lua_Number x14;
    lua_Number x15;
    lua_Number x16;
    lua_Number x17;
    lua_Number x18;
    lua_Number x19;
    lua_Number x20;
    lua_Number x21;
    lua_Number x22;
    lua_Number x23;
    lua_Number x24;
    lua_Number x25;
    lua_Number x26;
    lua_Number x27;
    lua_Number x28;
    lua_Number x29;
    lua_Number x30;
    lua_Number x31;
    lua_Number x32;
    lua_Number x33;
    lua_Number x34;
    lua_Number x35;
    lua_Number x36;
    lua_Number x37;
    lua_Number x38;
    lua_Number x39;
    lua_Number x40;
    lua_Number x41;
    lua_Number x42;
    lua_Number x43;
    	
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[22].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                12, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x11 = fltvalue(slot);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[22].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                12, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x12 = fltvalue(slot);
    }
    x4 = x11 - x12;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[25].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                13, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x13 = fltvalue(slot);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[25].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                13, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x14 = fltvalue(slot);
    }
    x5 = x13 - x14;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[28].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                14, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x15 = fltvalue(slot);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[28].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                14, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x16 = fltvalue(slot);
    }
    x6 = x15 - x16;
    x19 = x4 * x4;
    x20 = x5 * x5;
    x18 = x19 + x20;
    x21 = x6 * x6;
    x17 = x18 + x21;
    x7 = sqrt(x17);
    x23 = x7 * x7;
    x22 = x23 * x7;
    x8 = x3 / x22;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[13].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                19, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x24 = fltvalue(slot);
    }
    x9 = x24 * x8;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[21].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                20, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x26 = fltvalue(slot);
    }
    x27 = x4 * x9;
    x25 = x26 - x27;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[21].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[21].uv));
            slot = luaH_newkey(L, x1, &keyv);
        }
        setfltvalue(slot, x25);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[24].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                21, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x29 = fltvalue(slot);
    }
    x30 = x5 * x9;
    x28 = x29 - x30;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[24].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[24].uv));
            slot = luaH_newkey(L, x1, &keyv);
        }
        setfltvalue(slot, x28);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[27].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                22, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x32 = fltvalue(slot);
    }
    x33 = x6 * x9;
    x31 = x32 - x33;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[27].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[27].uv));
            slot = luaH_newkey(L, x1, &keyv);
        }
        setfltvalue(slot, x31);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[13].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                24, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x34 = fltvalue(slot);
    }
    x10 = x34 * x8;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[21].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                25, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x36 = fltvalue(slot);
    }
    x37 = x4 * x10;
    x35 = x36 + x37;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[21].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[21].uv));
            slot = luaH_newkey(L, x2, &keyv);
        }
        setfltvalue(slot, x35);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[24].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                26, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x39 = fltvalue(slot);
    }
    x40 = x5 * x10;
    x38 = x39 + x40;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[24].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[24].uv));
            slot = luaH_newkey(L, x2, &keyv);
        }
        setfltvalue(slot, x38);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[27].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                27, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x42 = fltvalue(slot);
    }
    x43 = x6 * x10;
    x41 = x42 + x43;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x2, tsvalue(&G->uv[27].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[27].uv));
            slot = luaH_newkey(L, x2, &keyv);
        }
        setfltvalue(slot, x41);
    }
    	
  done:
    return;
}

/* update_position size_comparison/nbodyTable_pln.pln:30 */
static void function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1, /* bi */
    lua_Number x2  /* dt */
) {
    lua_Number x3;
    lua_Number x4;
    lua_Number x5;
    lua_Number x6;
    lua_Number x7;
    lua_Number x8;
    lua_Number x9;
    lua_Number x10;
    lua_Number x11;
    lua_Number x12;
    lua_Number x13;
    lua_Number x14;
    	
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[22].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                31, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x4 = fltvalue(slot);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[21].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                31, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x6 = fltvalue(slot);
    }
    x5 = x2 * x6;
    x3 = x4 + x5;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[22].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[22].uv));
            slot = luaH_newkey(L, x1, &keyv);
        }
        setfltvalue(slot, x3);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[25].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                32, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x8 = fltvalue(slot);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[24].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                32, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x10 = fltvalue(slot);
    }
    x9 = x2 * x10;
    x7 = x8 + x9;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[25].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[25].uv));
            slot = luaH_newkey(L, x1, &keyv);
        }
        setfltvalue(slot, x7);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[28].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                33, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x12 = fltvalue(slot);
    }
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[27].uv), &cache);
        if (PALLENE_UNLIKELY(!ttisfloat(slot))) {
            pallene_runtime_tag_check_error(L,
                33, LUA_TNUMFLT, rawtt(slot),
                "table field");
        }
        x14 = fltvalue(slot);
    }
    x13 = x2 * x14;
    x11 = x12 + x13;
    {
        static size_t cache = UINT_MAX;
        TValue *slot = pallene_getshortstr(x1, tsvalue(&G->uv[28].uv), &cache);
        if (PALLENE_UNLIKELY(isabstkey(slot))) {
            TValue keyv;
            setsvalue(L, &keyv, tsvalue(&G->uv[28].uv));
            slot = luaH_newkey(L, x1, &keyv);
        }
        setfltvalue(slot, x11);
    }
    	
  done:
    return;
}

/* advance size_comparison/nbodyTable_pln.pln:36 */
static void function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* nsteps */
    Table * x2, /* bodies */
    lua_Number x3  /* dt */
) {
    luaD_checkstack(L, 2);
    lua_Integer x4; /* n */
    lua_Integer x5; /* _ */
    lua_Integer x6; /* i */
    Table * x7; /* bi */
    lua_Integer x8; /* j */
    Table * x9; /* bj */
    lua_Integer x10; /* i */
    Table * x11; /* bi */
    lua_Integer x12;
    	
    x4 = luaH_getn(x2);
    for(
        lua_Integer start01 = 1, limit01 = x1, step01 = 1;
        (step01 >= 0 ? start01 <= limit01 : start01 >= limit01);
        start01 = intop(+, start01, step01)
    ){
        x5 = start01;
        for(
            lua_Integer start02 = 1, limit02 = x4, step02 = 1;
            (step02 >= 0 ? start02 <= limit02 : start02 >= limit02);
            start02 = intop(+, start02, step02)
        ){
            x6 = start02;
            {
                pallene_renormalize_array(L, x2, x6, 40);
                TValue *slot = &x2->array[x6 - 1];
                if (PALLENE_UNLIKELY(!ttistable(slot))) {
                    pallene_runtime_tag_check_error(L,
                        40, LUA_TTABLE, rawtt(slot),
                        "array element");
                }
                x7 = hvalue(slot);
            }
            sethvalue(L, s2v(base + 0), x7);
            x12 = intop(+, x6, 1);
            for(
                lua_Integer start03 = x12, limit03 = x4, step03 = 1;
                (step03 >= 0 ? start03 <= limit03 : start03 >= limit03);
                start03 = intop(+, start03, step03)
            ){
                x8 = start03;
                {
                    pallene_renormalize_array(L, x2, x8, 42);
                    TValue *slot = &x2->array[x8 - 1];
                    if (PALLENE_UNLIKELY(!ttistable(slot))) {
                        pallene_runtime_tag_check_error(L,
                            42, LUA_TTABLE, rawtt(slot),
                            "array element");
                    }
                    x9 = hvalue(slot);
                }
                sethvalue(L, s2v(base + 1), x9);
                {
                    StackValue *old_stack = L->stack;
                    function_02(L, G, base + 2, x7, x9, x3);
                    base = L->stack + (base - old_stack);
                }
            }
        }
        for(
            lua_Integer start04 = 1, limit04 = x4, step04 = 1;
            (step04 >= 0 ? start04 <= limit04 : start04 >= limit04);
            start04 = intop(+, start04, step04)
        ){
            x10 = start04;
            {
                pallene_renormalize_array(L, x2, x10, 47);
                TValue *slot = &x2->array[x10 - 1];
                if (PALLENE_UNLIKELY(!ttistable(slot))) {
                    pallene_runtime_tag_check_error(L,
                        47, LUA_TTABLE, rawtt(slot),
                        "array element");
                }
                x11 = hvalue(slot);
            }
            sethvalue(L, s2v(base + 0), x11);
            {
                StackValue *old_stack = L->stack;
                function_03(L, G, base + 1, x11, x3);
                base = L->stack + (base - old_stack);
            }
        }
    }
    	
  done:
    return;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_04_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 3)) {
        pallene_runtime_arity_error(L, "advance", 3, nargs);
    }
    	
    lua_Integer x1;
    Table * x2;
    lua_Number x3;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            36, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "nsteps");
    }
    x1 = ivalue(s2v(base + 1));
    	
    if (PALLENE_UNLIKELY(!ttistable(s2v(base + 2)))) {
        pallene_runtime_tag_check_error(L,
            36, LUA_TTABLE, rawtt(s2v(base + 2)),
            "argument '%s'", "bodies");
    }
    x2 = hvalue(s2v(base + 2));
    	
    if (PALLENE_UNLIKELY(!ttisfloat(s2v(base + 3)))) {
        pallene_runtime_tag_check_error(L,
            36, LUA_TNUMFLT, rawtt(s2v(base + 3)),
            "argument '%s'", "dt");
    }
    x3 = fltvalue(s2v(base + 3));
    	
    function_04(L, G, L->top, x1, x2, x3);
    return 0;
}

int luaopen_size_comparison_nbodyTable_pln(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 29);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 2, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_04_lua, 1);
    lua_seti(L, closures, 2);
    	
    /* Global values */
    	
    lua_pushstring(L, "x");
    lua_setiuservalue(L, globals, 1);
    	
    lua_pushstring(L, "x");
    lua_setiuservalue(L, globals, 2);
    	
    lua_pushstring(L, "y");
    lua_setiuservalue(L, globals, 3);
    	
    lua_pushstring(L, "y");
    lua_setiuservalue(L, globals, 4);
    	
    lua_pushstring(L, "z");
    lua_setiuservalue(L, globals, 5);
    	
    lua_pushstring(L, "z");
    lua_setiuservalue(L, globals, 6);
    	
    lua_pushstring(L, "mass");
    lua_setiuservalue(L, globals, 7);
    	
    lua_pushstring(L, "vx");
    lua_setiuservalue(L, globals, 8);
    	
    lua_pushstring(L, "vx");
    lua_setiuservalue(L, globals, 9);
    	
    lua_pushstring(L, "vy");
    lua_setiuservalue(L, globals, 10);
    	
    lua_pushstring(L, "vy");
    lua_setiuservalue(L, globals, 11);
    	
    lua_pushstring(L, "vz");
    lua_setiuservalue(L, globals, 12);
    	
    lua_pushstring(L, "vz");
    lua_setiuservalue(L, globals, 13);
    	
    lua_pushstring(L, "mass");
    lua_setiuservalue(L, globals, 14);
    	
    lua_pushstring(L, "vx");
    lua_setiuservalue(L, globals, 15);
    	
    lua_pushstring(L, "vx");
    lua_setiuservalue(L, globals, 16);
    	
    lua_pushstring(L, "vy");
    lua_setiuservalue(L, globals, 17);
    	
    lua_pushstring(L, "vy");
    lua_setiuservalue(L, globals, 18);
    	
    lua_pushstring(L, "vz");
    lua_setiuservalue(L, globals, 19);
    	
    lua_pushstring(L, "vz");
    lua_setiuservalue(L, globals, 20);
    	
    lua_pushstring(L, "x");
    lua_setiuservalue(L, globals, 21);
    	
    lua_pushstring(L, "vx");
    lua_setiuservalue(L, globals, 22);
    	
    lua_pushstring(L, "x");
    lua_setiuservalue(L, globals, 23);
    	
    lua_pushstring(L, "y");
    lua_setiuservalue(L, globals, 24);
    	
    lua_pushstring(L, "vy");
    lua_setiuservalue(L, globals, 25);
    	
    lua_pushstring(L, "y");
    lua_setiuservalue(L, globals, 26);
    	
    lua_pushstring(L, "z");
    lua_setiuservalue(L, globals, 27);
    	
    lua_pushstring(L, "vz");
    lua_setiuservalue(L, globals, 28);
    	
    lua_pushstring(L, "z");
    lua_setiuservalue(L, globals, 29);
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "advance");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

