/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static int function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1, /* a */
    lua_Integer x2, /* n */
    lua_Integer x3  /* c */
);
static void function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* N */
    Table * x2  /* a */
);
static void function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* N */
    Table * x2, /* a */
    lua_Integer x3  /* n */
);
static void function_05(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* N */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
  done:
    return;
}

/* isplaceok size_comparison/queen_pln.pln:2 */
static int function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table * x1, /* a */
    lua_Integer x2, /* n */
    lua_Integer x3  /* c */
) {
    int x4; /* ret1 */
    lua_Integer x5; /* i */
    lua_Integer x6; /* d */
    lua_Integer x7;
    int x8;
    lua_Integer x9;
    lua_Integer x10;
    lua_Integer x11;
    lua_Integer x12;
    	
    x7 = intop(-, x2, 1);
    for(
        lua_Integer start01 = 1, limit01 = x7, step01 = 1;
        (step01 >= 0 ? start01 <= limit01 : start01 >= limit01);
        start01 = intop(+, start01, step01)
    ){
        x5 = start01;
        {
            pallene_renormalize_array(L, x1, x5, 4);
            TValue *slot = &x1->array[x5 - 1];
            if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                pallene_runtime_tag_check_error(L,
                    4, LUA_TNUMINT, rawtt(slot),
                    "array element");
            }
            x6 = ivalue(slot);
        }
        x8 = (x6 == x3);
        if (!x8) {
            x9 = intop(-, x6, x5);
            x10 = intop(-, x3, x2);
            x8 = (x9 == x10);
        }
        if (!x8) {
            x11 = intop(+, x6, x5);
            x12 = intop(+, x3, x2);
            x8 = (x11 == x12);
        }
        if (x8) {
            x4 = 0;
            goto done;
        }
    }
    x4 = 1;
    goto done;
    	
  done:
    return x4;
}

/* printsolution size_comparison/queen_pln.pln:16 */
static void function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* N */
    Table * x2  /* a */
) {
    lua_Integer x3; /* i */
    lua_Integer x4; /* ai */
    lua_Integer x5; /* j */
    int x6;
    	
    for(
        lua_Integer start02 = 1, limit02 = x1, step02 = 1;
        (step02 >= 0 ? start02 <= limit02 : start02 >= limit02);
        start02 = intop(+, start02, step02)
    ){
        x3 = start02;
        {
            pallene_renormalize_array(L, x2, x3, 18);
            TValue *slot = &x2->array[x3 - 1];
            if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
                pallene_runtime_tag_check_error(L,
                    18, LUA_TNUMINT, rawtt(slot),
                    "array element");
            }
            x4 = ivalue(slot);
        }
        for(
            lua_Integer start03 = 1, limit03 = x1, step03 = 1;
            (step03 >= 0 ? start03 <= limit03 : start03 >= limit03);
            start03 = intop(+, start03, step03)
        ){
            x5 = start03;
            x6 = (x4 == x5);
            if (x6) {
                pallene_io_write(L, tsvalue(&G->uv[0].uv));
            } else {
                pallene_io_write(L, tsvalue(&G->uv[1].uv));
            }
            pallene_io_write(L, tsvalue(&G->uv[2].uv));
        }
        pallene_io_write(L, tsvalue(&G->uv[4].uv));
    }
    pallene_io_write(L, tsvalue(&G->uv[4].uv));
    	
  done:
    return;
}

/* addqueen size_comparison/queen_pln.pln:34 */
static void function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* N */
    Table * x2, /* a */
    lua_Integer x3  /* n */
) {
    lua_Integer x4; /* c */
    int x5;
    int x6;
    lua_Integer x7;
    	
    x5 = (x3 > x1);
    if (x5) {
        {
            StackValue *old_stack = L->stack;
            function_03(L, G, base + 0, x1, x2);
            base = L->stack + (base - old_stack);
        }
    } else {
        for(
            lua_Integer start04 = 1, limit04 = x1, step04 = 1;
            (step04 >= 0 ? start04 <= limit04 : start04 >= limit04);
            start04 = intop(+, start04, step04)
        ){
            x4 = start04;
            {
                StackValue *old_stack = L->stack;
                x6 = function_02(L, G, base + 0, x2, x3, x4);
                base = L->stack + (base - old_stack);
            }
            if (x6) {
                {
                    pallene_renormalize_array(L, x2, x3, 40);
                    TValue *slot = &x2->array[x3 - 1];
                    setivalue(slot, x4);
                }
                x7 = intop(+, x3, 1);
                {
                    StackValue *old_stack = L->stack;
                    function_04(L, G, base + 0, x1, x2, x7);
                    base = L->stack + (base - old_stack);
                }
            }
        }
    }
    	
  done:
    return;
}

/* nqueens size_comparison/queen_pln.pln:48 */
static void function_05(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* N */
) {
    luaD_checkstack(L, 1);
    Table * x2;
    	
    x2 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 0), x2);
    luaC_condGC(L, L->top = base + 1, (void)0);
    {
        StackValue *old_stack = L->stack;
        function_04(L, G, base + 1, x1, x2, 1);
        base = L->stack + (base - old_stack);
    }
    	
  done:
    return;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_05_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "nqueens", 1, nargs);
    }
    	
    lua_Integer x1;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            48, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "N");
    }
    x1 = ivalue(s2v(base + 1));
    	
    function_05(L, G, L->top, x1);
    return 0;
}

int luaopen_size_comparison_queen_pln(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 5);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 2, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_05_lua, 1);
    lua_seti(L, closures, 2);
    	
    /* Global values */
    	
    lua_pushstring(L, "X");
    lua_setiuservalue(L, globals, 1);
    	
    lua_pushstring(L, "-");
    lua_setiuservalue(L, globals, 2);
    	
    lua_pushstring(L, " ");
    lua_setiuservalue(L, globals, 3);
    	
    lua_pushstring(L, "\n");
    lua_setiuservalue(L, globals, 4);
    	
    lua_pushstring(L, "\n");
    lua_setiuservalue(L, globals, 5);
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "nqueens");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

