/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* Stream */

static Udata *crecord_01_new(lua_State *L, Udata *G)
{
    Udata *rec = luaS_newudata(L, 0, 3);
    rec->metatable = hvalue(&G->uv[0].uv);
    return rec;
}

/* Closure2 */

typedef struct {
    lua_Integer f01; /* n */
} crecord_02;

inline
static crecord_02 *crecord_02_prims(Udata *u)
{
    char *p = cast_charp(u) + udatamemoffset(1);
    return (crecord_02 *) p;
}

static Udata *crecord_02_new(lua_State *L, Udata *G)
{
    Udata *rec = luaS_newudata(L, sizeof(crecord_02), 1);
    rec->metatable = hvalue(&G->uv[1].uv);
    return rec;
}

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static Udata * function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    TValue x1, /* head */
    TValue x2, /* state */
    TValue x3  /* get_tail */
);
static TValue function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* st */
);
static Udata * function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* st */
);
static TValue function_05(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1, /* st */
    lua_Integer x2  /* n */
);
static Udata * function_06(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* n */
);
static Udata * function_07(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* i */
);
static Udata * function_08(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* n */
    Udata * x2  /* st */
);
static Udata * function_09(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* state */
);
static Udata * function_10(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* st */
);
static Udata * function_11(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* state */
);
static lua_Integer function_12(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* n */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
  done:
    return;
}

/* make_stream size_comparison/streamSieve_pln.pln:12 */
static Udata * function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    TValue x1, /* head */
    TValue x2, /* state */
    TValue x3  /* get_tail */
) {
    luaD_checkstack(L, 1);
    Udata * x4; /* ret1 */
    TValue x5;
    	
    x4 = crecord_01_new(L, G);
    setuvalue(L, s2v(base + 0), x4);
    luaC_condGC(L, L->top = base + 1, (void)0);
    setobj(L, &x4->uv[0].uv, &x1);
    pallene_barrierback_unknown_child(L, x4, &x1);
    setobj(L, &x4->uv[1].uv, &x2);
    pallene_barrierback_unknown_child(L, x4, &x2);
    if (PALLENE_UNLIKELY(!ttisfunction(&x3))) {
        pallene_runtime_tag_check_error(L,
            13, LUA_TFUNCTION, rawtt(&x3),
            "downcasted value");
    }
    x5 = *(&x3);
    setobj(L, &x4->uv[2].uv, &x5);
    pallene_barrierback_unknown_child(L, x4, &x5);
    goto done;
    	
  done:
    return x4;
}

/* stream_head size_comparison/streamSieve_pln.pln:16 */
static TValue function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* st */
) {
    TValue x2; /* ret1 */
    	
    x2 = *(&x1->uv[0].uv);
    goto done;
    	
  done:
    return x2;
}

/* stream_tail size_comparison/streamSieve_pln.pln:20 */
static Udata * function_04(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* st */
) {
    luaD_checkstack(L, 3);
    Udata * x2; /* ret1 */
    TValue x3;
    TValue x4;
    TValue x5;
    	
    x4 = *(&x1->uv[2].uv);
    x5 = *(&x1->uv[1].uv);
    setobj(L, s2v(base + 0), &x5);
    {
        StackValue *old_stack = L->stack;
        L->top = base + 1;
        setobj(L, s2v(L->top), &x4);
        L->top++;
        setobj(L, s2v(L->top), &x5);
        L->top++;
        lua_call(L, 1, 1);
        {
            L->top--;
            TValue *slot = s2v(L->top);
            x3 = *(slot);
        }
        base = L->stack + (base - old_stack);
    }
    if (PALLENE_UNLIKELY(!(ttisfulluserdata(&x3) && uvalue(&x3)->metatable == hvalue(&G->uv[0].uv)))) {
        pallene_runtime_tag_check_error(L,
            21, LUA_TUSERDATA, rawtt(&x3),
            "downcasted value");
    }
    x2 = uvalue(&x3);
    goto done;
    	
  done:
    return x2;
}

/* stream_get size_comparison/streamSieve_pln.pln:24 */
static TValue function_05(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1, /* st */
    lua_Integer x2  /* n */
) {
    luaD_checkstack(L, 1);
    TValue x3; /* ret1 */
    lua_Integer x4; /* _ */
    lua_Integer x5;
    	
    x5 = intop(-, x2, 1);
    for(
        lua_Integer start01 = 1, limit01 = x5, step01 = 1;
        (step01 >= 0 ? start01 <= limit01 : start01 >= limit01);
        start01 = intop(+, start01, step01)
    ){
        x4 = start01;
        {
            StackValue *old_stack = L->stack;
            x1 = function_04(L, G, base + 0, x1);
            base = L->stack + (base - old_stack);
        }
        setuvalue(L, s2v(base + 0), x1);
    }
    {
        StackValue *old_stack = L->stack;
        x3 = function_03(L, G, base + 1, x1);
        base = L->stack + (base - old_stack);
    }
    goto done;
    	
  done:
    return x3;
}

/* count_from size_comparison/streamSieve_pln.pln:35 */
static Udata * function_06(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* n */
) {
    luaD_checkstack(L, 3);
    Udata * x2; /* ret1 */
    TValue x3;
    TValue x4;
    TValue x5;
    	
    setivalue(&x3, x1);
    setobj(L, s2v(base + 0), &x3);
    setivalue(&x4, x1);
    setobj(L, s2v(base + 1), &x4);
    setobj(L, &x5, &*(&G->uv[2].uv));
    setobj(L, s2v(base + 2), &x5);
    {
        StackValue *old_stack = L->stack;
        x2 = function_02(L, G, base + 3, x3, x4, x5);
        base = L->stack + (base - old_stack);
    }
    goto done;
    	
  done:
    return x2;
}

/* _tail1 size_comparison/streamSieve_pln.pln:39 */
static Udata * function_07(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* i */
) {
    Udata * x2; /* ret1 */
    lua_Integer x3;
    	
    x3 = intop(+, x1, 1);
    {
        StackValue *old_stack = L->stack;
        x2 = function_06(L, G, base + 0, x3);
        base = L->stack + (base - old_stack);
    }
    goto done;
    	
  done:
    return x2;
}

/* sift size_comparison/streamSieve_pln.pln:50 */
static Udata * function_08(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* n */
    Udata * x2  /* st */
) {
    luaD_checkstack(L, 5);
    Udata * x3; /* ret1 */
    lua_Integer x4; /* hd */
    Udata * x5; /* tl */
    Udata * x6; /* state */
    TValue x7;
    int x8;
    lua_Integer x9;
    TValue x10;
    TValue x11;
    TValue x12;
    TValue x13;
    	
    {
        StackValue *old_stack = L->stack;
        x7 = function_03(L, G, base + 0, x2);
        base = L->stack + (base - old_stack);
    }
    if (PALLENE_UNLIKELY(!ttisinteger(&x7))) {
        pallene_runtime_tag_check_error(L,
            51, LUA_TNUMINT, rawtt(&x7),
            "downcasted value");
    }
    x4 = ivalue(&x7);
    {
        StackValue *old_stack = L->stack;
        x5 = function_04(L, G, base + 0, x2);
        base = L->stack + (base - old_stack);
    }
    setuvalue(L, s2v(base + 0), x5);
    while (1) {
        x9 = pallene_int_modi(L, x4, x1, 53);
        x8 = (x9 == 0);
        if (!x8) {
            break;
        }
        x2 = x5;
        setuvalue(L, s2v(base + 1), x2);
        {
            StackValue *old_stack = L->stack;
            x10 = function_03(L, G, base + 2, x2);
            base = L->stack + (base - old_stack);
        }
        if (PALLENE_UNLIKELY(!ttisinteger(&x10))) {
            pallene_runtime_tag_check_error(L,
                55, LUA_TNUMINT, rawtt(&x10),
                "downcasted value");
        }
        x4 = ivalue(&x10);
        {
            StackValue *old_stack = L->stack;
            x5 = function_04(L, G, base + 2, x2);
            base = L->stack + (base - old_stack);
        }
        setuvalue(L, s2v(base + 0), x5);
    }
    x6 = crecord_02_new(L, G);
    setuvalue(L, s2v(base + 1), x6);
    luaC_condGC(L, L->top = base + 2, (void)0);
    crecord_02_prims(x6)->f01 = x1;
    setuvalue(L, &x6->uv[0].uv, x5);
    pallene_barrierback_collectable_child(L, x6, x5);
    setivalue(&x11, x4);
    setobj(L, s2v(base + 2), &x11);
    setuvalue(L, &x12, x6);
    setobj(L, s2v(base + 3), &x12);
    setobj(L, &x13, &*(&G->uv[3].uv));
    setobj(L, s2v(base + 4), &x13);
    {
        StackValue *old_stack = L->stack;
        x3 = function_02(L, G, base + 5, x11, x12, x13);
        base = L->stack + (base - old_stack);
    }
    goto done;
    	
  done:
    return x3;
}

/* _tail2 size_comparison/streamSieve_pln.pln:62 */
static Udata * function_09(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* state */
) {
    luaD_checkstack(L, 1);
    Udata * x2; /* ret1 */
    lua_Integer x3;
    Udata * x4;
    	
    x3 = crecord_02_prims(x1)->f01;
    x4 = uvalue(&x1->uv[0].uv);
    setuvalue(L, s2v(base + 0), x4);
    {
        StackValue *old_stack = L->stack;
        x2 = function_08(L, G, base + 1, x3, x4);
        base = L->stack + (base - old_stack);
    }
    goto done;
    	
  done:
    return x2;
}

/* sieve size_comparison/streamSieve_pln.pln:68 */
static Udata * function_10(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* st */
) {
    luaD_checkstack(L, 3);
    Udata * x2; /* ret1 */
    TValue x3; /* n */
    Udata * x4; /* tl */
    Udata * x5; /* state */
    lua_Integer x6;
    TValue x7;
    TValue x8;
    	
    {
        StackValue *old_stack = L->stack;
        x3 = function_03(L, G, base + 0, x1);
        base = L->stack + (base - old_stack);
    }
    setobj(L, s2v(base + 0), &x3);
    {
        StackValue *old_stack = L->stack;
        x4 = function_04(L, G, base + 1, x1);
        base = L->stack + (base - old_stack);
    }
    setuvalue(L, s2v(base + 1), x4);
    x5 = crecord_02_new(L, G);
    setuvalue(L, s2v(base + 2), x5);
    luaC_condGC(L, L->top = base + 3, (void)0);
    if (PALLENE_UNLIKELY(!ttisinteger(&x3))) {
        pallene_runtime_tag_check_error(L,
            71, LUA_TNUMINT, rawtt(&x3),
            "downcasted value");
    }
    x6 = ivalue(&x3);
    crecord_02_prims(x5)->f01 = x6;
    setuvalue(L, &x5->uv[0].uv, x4);
    pallene_barrierback_collectable_child(L, x5, x4);
    setuvalue(L, &x7, x5);
    setobj(L, s2v(base + 1), &x7);
    setobj(L, &x8, &*(&G->uv[4].uv));
    setobj(L, s2v(base + 2), &x8);
    {
        StackValue *old_stack = L->stack;
        x2 = function_02(L, G, base + 3, x3, x7, x8);
        base = L->stack + (base - old_stack);
    }
    goto done;
    	
  done:
    return x2;
}

/* _tail3 size_comparison/streamSieve_pln.pln:75 */
static Udata * function_11(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Udata * x1  /* state */
) {
    luaD_checkstack(L, 1);
    Udata * x2; /* ret1 */
    Udata * x3;
    lua_Integer x4;
    Udata * x5;
    	
    x4 = crecord_02_prims(x1)->f01;
    x5 = uvalue(&x1->uv[0].uv);
    setuvalue(L, s2v(base + 0), x5);
    {
        StackValue *old_stack = L->stack;
        x3 = function_08(L, G, base + 1, x4, x5);
        base = L->stack + (base - old_stack);
    }
    setuvalue(L, s2v(base + 0), x3);
    {
        StackValue *old_stack = L->stack;
        x2 = function_10(L, G, base + 1, x3);
        base = L->stack + (base - old_stack);
    }
    goto done;
    	
  done:
    return x2;
}

/* get_prime size_comparison/streamSieve_pln.pln:81 */
static lua_Integer function_12(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* n */
) {
    luaD_checkstack(L, 1);
    lua_Integer x2; /* ret1 */
    Udata * x3; /* prime_stream */
    Udata * x4;
    TValue x5;
    	
    {
        StackValue *old_stack = L->stack;
        x4 = function_06(L, G, base + 0, 2);
        base = L->stack + (base - old_stack);
    }
    setuvalue(L, s2v(base + 0), x4);
    {
        StackValue *old_stack = L->stack;
        x3 = function_10(L, G, base + 1, x4);
        base = L->stack + (base - old_stack);
    }
    setuvalue(L, s2v(base + 0), x3);
    {
        StackValue *old_stack = L->stack;
        x5 = function_05(L, G, base + 1, x3, x1);
        base = L->stack + (base - old_stack);
    }
    if (PALLENE_UNLIKELY(!ttisinteger(&x5))) {
        pallene_runtime_tag_check_error(L,
            83, LUA_TNUMINT, rawtt(&x5),
            "downcasted value");
    }
    x2 = ivalue(&x5);
    goto done;
    	
  done:
    return x2;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_07_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "_tail1", 1, nargs);
    }
    	
    lua_Integer x1;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            39, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "i");
    }
    x1 = ivalue(s2v(base + 1));
    	
    Udata * ret1;
    ret1 = function_07(L, G, L->top, x1);
    setuvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_09_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "_tail2", 1, nargs);
    }
    	
    Udata * x1;
    	
    if (PALLENE_UNLIKELY(!(ttisfulluserdata(s2v(base + 1)) && uvalue(s2v(base + 1))->metatable == hvalue(&G->uv[1].uv)))) {
        pallene_runtime_tag_check_error(L,
            62, LUA_TUSERDATA, rawtt(s2v(base + 1)),
            "argument '%s'", "state");
    }
    x1 = uvalue(s2v(base + 1));
    	
    Udata * ret1;
    ret1 = function_09(L, G, L->top, x1);
    setuvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_11_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "_tail3", 1, nargs);
    }
    	
    Udata * x1;
    	
    if (PALLENE_UNLIKELY(!(ttisfulluserdata(s2v(base + 1)) && uvalue(s2v(base + 1))->metatable == hvalue(&G->uv[1].uv)))) {
        pallene_runtime_tag_check_error(L,
            75, LUA_TUSERDATA, rawtt(s2v(base + 1)),
            "argument '%s'", "state");
    }
    x1 = uvalue(s2v(base + 1));
    	
    Udata * ret1;
    ret1 = function_11(L, G, L->top, x1);
    setuvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_12_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "get_prime", 1, nargs);
    }
    	
    lua_Integer x1;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            81, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "n");
    }
    x1 = ivalue(s2v(base + 1));
    	
    lua_Integer ret1;
    ret1 = function_12(L, G, L->top, x1);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

int luaopen_size_comparison_streamSieve_pln(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 5);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 5, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_07_lua, 1);
    lua_seti(L, closures, 2);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_09_lua, 1);
    lua_seti(L, closures, 3);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_11_lua, 1);
    lua_seti(L, closures, 4);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_12_lua, 1);
    lua_seti(L, closures, 5);
    	
    /* Global values */
    	
    lua_newtable(L);
    lua_pushstring(L, "__metatable");
    lua_pushboolean(L, 0);
    lua_settable(L, -3);
    lua_setiuservalue(L, globals, 1);
    	
    lua_newtable(L);
    lua_pushstring(L, "__metatable");
    lua_pushboolean(L, 0);
    lua_settable(L, -3);
    lua_setiuservalue(L, globals, 2);
    	
    lua_geti(L, closures, 2);
    lua_setiuservalue(L, globals, 3);
    	
    lua_geti(L, closures, 3);
    lua_setiuservalue(L, globals, 4);
    	
    lua_geti(L, closures, 4);
    lua_setiuservalue(L, globals, 5);
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "get_prime");
    lua_geti(L, closures, 5);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

